name: âœ” Test

on:
  push:
    tags: ["**"]
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  sharpalignment:
    name: ðŸŸ£ .NET Tool
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: ðŸ›’ Checkout
        uses: actions/checkout@v4

      - name: ðŸŸ£ Setup .NET
        uses: actions/setup-dotnet@v4

      - name: ðŸ› ï¸ Build
        run: >
          dotnet build 
          --configuration Release

      - name: âœ” Test
        run: >
          dotnet test
          --configuration Release
          --no-build

      - name: ðŸ“¦ï¸ Pack .NET tool
        run: >
          dotnet pack
          --output ./
          ./SharpAlignment.Console/SharpAlignment.Console.csproj

      - name: ðŸ“¤ Upload NUPKG artifact
        uses: actions/upload-artifact@v4
        with:
          name: sharpalignment
          path: src/*.nupkg
          if-no-files-found: error
          retention-days: 1

      - name: ðŸ“¦ Publish self-contained Linux binary
        run: >
          dotnet publish
          ./SharpAlignment.Console/SharpAlignment.Console.csproj
          --configuration Release
          --runtime linux-x64
          --self-contained true
          -p:PublishSingleFile=true
          --output ../artifacts/publish/linux-x64

      - name: ðŸ“¦ Publish self-contained Windows binary
        run: >
          dotnet publish
          ./SharpAlignment.Console/SharpAlignment.Console.csproj
          --configuration Release
          --runtime win-x64
          --self-contained true
          -p:PublishSingleFile=true
          --output ../artifacts/publish/win-x64

      - name: ðŸ“¤ Upload self-contained binaries artifact
        uses: actions/upload-artifact@v4
        with:
          name: sharpalignment-self-contained
          path: |
            artifacts/publish/linux-x64/sharpalignment
            artifacts/publish/win-x64/sharpalignment.exe
          if-no-files-found: error
          retention-days: 1

  release-sync:
    name: âœ¨ Release Sync
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    outputs:
      created-src: ${{ steps.release.outputs.src--release_created }}
    steps:
      - name: âœ¨ Create/Update release PR
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          config-file: release-config.json
          manifest-file: release-manifest.json
